name: Docker Image CI

on:
  push:
    branches: ["main"]

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
          cache-to: type=inline
          platforms: linux/amd64
          push: true
          build-args: |
            GIT_SHA=${{ github.sha }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest,ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
          target: bot

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.RELAYDON_HOST }}
          username: ${{ secrets.RELAYDON_USER }}
          key: ${{ secrets.RELAYDON_KEY }}
          port: 22
          script: |
            echo "Deploying ${{ github.sha }}"
            cd /root/relaydon
            sed -i 's|^BOT_IMAGE=.*|BOT_IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:'${{ github.sha }}'|' .env
            docker compose pull --quiet bot
            docker compose up --detach --timeout 5 --no-deps --remove-orphans bot
            docker compose ps
